model:
  name: 'MinkUNet34'
  in_feat_size: 1
  out_classes: 13

# 这个地方如果是对SemanticPOSS来说的话就是mini，对SemanticKITTI就是full
dataset:
  version: 'mini'
  name: 'SynLiDAR'
  dataset_path: 'data/SynLiDAR/mini'
  mapping_path: '_resources/synlidar_semanticposs.yaml'
  target: 'SemanticPOSS'
  voxel_size: 0.05
  num_pts: 50000
  ignore_label: -1
  augment_data: true


pipeline:
  epochs: 100
  steps: null
  gpus: [2]
  precision: 32
  loss: 'SoftDICELoss'
  seed: 1234
  save_dir: 'experiments/pretrained/synlidar/semanticposs'
  validate_target: true

  dataloader:
    batch_size: 4
    num_workers: 16

  optimizer:
    name: 'SGD'
    lr: 0.01

  scheduler:
    name: 'ExponentialLR'

  lightning:
    check_val_every_n_epoch: 5
    clear_cache_int: 1
    resume_checkpoint: null
    val_check_interval: 1.0
    num_sanity_val_steps: 0


  wandb:
    run_name: 'SOURCE-WARMUP-SynLiDAR2SemanticPOSS'
    project_name: 'cosmix'
    entity_name: 'liujxiao'
    offline: true
